apiVersion: v1
kind: Service
metadata:
  labels:
    app: kaiburr-mongo
  name: kaiburrmongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: kaiburr-mongo
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaiburr-mongo
  labels:
    app: kaiburr-mongo
spec:
  selector:
    matchLabels:
      app: kaiburr-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: kaiburr-mongo
      name: kaiburrmongodb


    spec:
      containers:
        - image: mongo:latest
          name: kaiburr-mongo

          ports:
            - containerPort: 27017
              name: kaiburr-mongo